### ISSUE TITLE
should add dependency of :Mail/RFC822/Address.pm and Test::Compile

### ISSUE THREAD

**Issue by ChinaXing** [dr-co/libmojolicious-plugin-human-perl#1]
I use cpam to install this plugin, i found that it install faield.

throught sudo cpanm -v Mojolicious::Plugin::Human, found that **Test::Compile** and **Mail/RFC822/Address.pm** missing .

I think you should add these package/module to your required module list.

hope fix it :)

**Comment by rshadow** [comment]
Already fixed
